# Generated by Django 4.2.7 on 2023-11-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialesReciclables',
            fields=[
                ('id_material', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('material', models.CharField(db_column='Material', max_length=40)),
                ('valor_puntos', models.IntegerField(db_column='Valor_Unitario_Puntos', max_length=4)),
            ],
        ),
    ]
