# Generated by Django 4.2.7 on 2023-11-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialesreciclables',
            name='valor_puntos',
            field=models.IntegerField(db_column='Valor_Unitario_Puntos'),
        ),
    ]
