# Generated by Django 4.2.7 on 2023-11-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_materialesreciclables_valor_puntos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialesReciclables',
            new_name='Material',
        ),
    ]
