# Generated by Django 4.2.7 on 2023-11-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_recompensa_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recompensa',
            table=None,
        ),
    ]
