# Generated by Django 4.2.7 on 2023-11-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_canjeables_delete_recompensa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canjeables',
            options={},
        ),
    ]
