# Generated by Django 4.2.7 on 2023-11-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_canjeables_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canjeables',
            name='recompensa',
            field=models.CharField(db_column='Recompensa', max_length=40, unique=True),
        ),
    ]
