# Generated by Django 4.2.7 on 2023-11-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_canjeables_recompensa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canjeables',
            name='id_recom',
            field=models.IntegerField(db_column='Id_Recompensa', primary_key=True, serialize=False, unique=True),
        ),
    ]
