# Generated by Django 4.2.7 on 2023-11-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_canjeables_id_recom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canjeables',
            name='recompensa',
            field=models.CharField(db_column='Recompensa', max_length=40),
        ),
    ]
