# Generated by Django 4.2.7 on 2023-11-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_canjeables_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='canjeables',
            name='categoria',
            field=models.CharField(db_column='Categoria', default='', max_length=20),
        ),
    ]
