# Generated by Django 4.2.7 on 2023-11-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_canjeables_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canjeables',
            name='id_recom',
            field=models.AutoField(db_column='Id_Recompensa', primary_key=True, serialize=False, unique=True),
        ),
    ]
