# Generated by Django 4.2.7 on 2023-12-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_canjeables_id_recom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
    ]
