# Generated by Django 4.2.7 on 2023-12-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False},
        ),
    ]
