# Generated by Django 4.2.7 on 2023-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usuario_date_joined_remove_usuario_fecha_nac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
